name: Deploy QA

on:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas (si las hubiera)
      run: echo "No hay pruebas aún"

    - name: Construir y subir imagen Docker
      run: |
        docker build -t balarai/hola-mundo-api:qa .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push balarai/hola-mundo-api:qa
